services:

  redis:
    image: redis:7-alpine
    container_name: dot_connection_app_redis
    restart: always
    ports:
      - "6389:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  backend:
    container_name: dot_connection_app_backend
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "5009:5009"

    depends_on:
      redis:
        condition: service_healthy

    volumes:
      - dot_connection_app_logs:/app/winston

    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5009/health"]
      interval: 30s
      retries: 3
      start_period: 40s
      timeout: 10s

volumes:
  dot_connection_app_logs: